name: eslint
on:
  - pull_request
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - run: yarn
      - name: eslint
        run: yarn lint
